paths:
  database: papers.db
  history: history
  cache: cache
  requests_cache: requests-cache
sentry:
  use: false
  dsn: ""
  traces_sample_rate: 1.0
  environment: dev
  log_level: INFO
  event_log_level: INFO
